SECRET_KEY_SETTINGS = #DJANGO DEFAULT APPLICATION SECRET
SECRET_EMAIL_HOST = #EMAIL SMTP 
SECRET_EMAIL_HOST_USER = #EMAIL LOGIN
SECRET_EMAIL_HOST_PASSWORD = #EMAIL PASSWORD
SECRET_DEFAULT_FROM_EMAIL = #EMAIL ACCOUNT NAME LIKE: 'PoloVota <NAME@DOMAIN.com.br>'